import pdfrw

from .basicas import *
from .objetos_classes import *




dict_pdf = {'Nome do Personagem': '',
            'Nome do Jogador': '',
            'Raca do Personagem': '',
            'Origem do Personagem': '',
            'Classe(s) do personagem': '',
            'Divindade': '',
            'ModFor': '',
            'ModDes': '',
            'ModCon': '',
            'ModInt': '',
            'ModSab': '',
            'ModCar': '',
            'Pontos de Vida m#C3#A1ximos': '',
            'Pontos de Vida atuais': '',
            'Pontos de Mana m#C3#A1ximos': '',
            'Pontos de Mana atuais': '',
            'Ataque 1': '',
            'Bonus do ataque 1': '',
            'Dano causado pelo ataque 1': '',
            'Margem de cr#C3#ADtico e multiplicador 1': '',
            'Tipo de dano do ataque 1': '',
            'Alcance do ataque 1': '',
            'Ataque 2': '',
            'Bonus do ataque 2': '',
            'Dano causado pelo ataque 2': '',
            'Margem de cr#C3#ADtico e multiplicador 2': '',
            'Tipo de dano do ataque 2': '',
            'Alcance do ataque 2': '',
            'Ataque 3': '',
            'Bonus do ataque 3': '',
            'Dano causado pelo ataque 3': '',
            'Margem de cr#C3#ADtico e multiplicador 3': '',
            'Tipo de dano do ataque 3': '',
            'Alcance do ataque 3': '',
            'Ataque 4': '',
            'Bonus do ataque 4': '',
            'Dano causado pelo ataque 4': '',
            'Margem de cr#C3#ADtico e multiplicador 4': '',
            'Tipo de dano do ataque 4': '',
            'Alcance do ataque 4': '',
            'Ataque 5': '',
            'Bonus do ataque 5': '',
            'Dano causado pelo ataque 5': '',
            'Margem de cr#C3#ADtico e multiplicador 5': '',
            'Tipo de dano do ataque 5': '',
            'Alcance do ataque 5': '',
            'Proficiencias e outras caracteristicas': '',
            'Experiencia total do personagem': '',
            'Deslocamento do personagem': '',
            'Item 1': '',
            'Quantidade Item 1': '',
            'Slots Item 1': '',
            'Item 2': '',
            'Quantidade Item 2': '',
            'Slots Item 2': '',
            'Item 3': '',
            'Quantidade Item 3': '',
            'Slots Item 3': '',
            'Item 4': '',
            'Quantidade Item 4': '',
            'Slots Item 4': '',
            'Item 5': '',
            'Quantidade Item 5': '',
            'Slots Item 5': '',
            'Item 6': '',
            'Quantidade Item 6': '',
            'Slots Item 6': '',
            'Item 7': '',
            'Quantidade Item 7': '',
            'Slots Item 7': '',
            'Item 8': '',
            'Quantidade Item 8': '',
            'Slots Item 8': '',
            'Item 9': '',
            'Quantidade Item 9': '',
            'Slots Item 9': '',
            'Item 10': '',
            'Quantidade Item 10': '',
            'Slots Item 10': '',
            'Item 11': '',
            'Quantidade Item 11': '',
            'Slots Item 11': '',
            'Item 12': '',
            'Quantidade Item 12': '',
            'Slots Item 12': '',
            'Item 13': '',
            'Quantidade Item 13': '',
            'Slots Item 13': '',
            'Item 14': '',
            'Quantidade Item 14': '',
            'Slots Item 14': '',
            'Item 15': '',
            'Quantidade Item 15': '',
            'Slots Item 15': '',
            'Item 16': '',
            'Quantidade Item 16': '',
            'Slots Item 16': '',
            'Item 17': '',
            'Quantidade Item 17': '',
            'Slots Item 17': '',
            'Tibares': '',
            'Limite de carga': '',
            'Descricao': '',
            'Habilidades de raca e origem': '',
            'Habilidades de Classe e poderes': '',
            'Teste de resistencias': '',
            'Magias': '',
            'Anotacoes': '',
            'Lv': '',
            'CA': '',
            'Base CA': '',
            'arm pesa': '',
            'SeleAtribDefe': '',
            'ModAtribDefe': '',
            'Arm': '',
            'Esc': '',
            'Arm1': '',
            'Esc2': '',
            'B': '',
            'Outros B': '',
            'PArmTotal': '',
            'Armadura': '',
            'Pa': '',
            'Escudo': '',
            'Pe': '',
            'SeleTamanho': '',
            'ModFurtTam': '',
            'ModManTam': '',
            'Mar Trei acro': '',
            '011': '',
            'SeleAtribAcro': '',
            '013': '',
            '014': '',
            'ModAtribAcro': '',
            'Mar Trei ades': '',
            '021': '',
            'SeleAtribAdes': '',
            '023': '',
            '024': '',
            'ModAtribAdes': '',
            'Mar Trei atle': '',
            '031': '',
            'SeleAtribAtle': '',
            '033': '',
            '034': '',
            'ModAtribAtle': '',
            'Mar Trei atua': '',
            '041': '',
            'SeleAtribAtua': '',
            '043': '',
            '044': '',
            'ModAtribAtua': '',
            'Mar Trei caval': '',
            '051': '',
            'SeleAtribCava': '',
            '053': '',
            '054': '',
            'ModAtribCava': '',
            'Mar Trei conhe': '',
            '061': '',
            'SeleAtribConh': '',
            '063': '',
            '064': '',
            'ModAtribConh': '',
            'Mar Trei cura': '',
            '071': '',
            'SeleAtribCura': '',
            '073': '',
            '074': '',
            'ModAtribCura': '',
            'Mar Trei dipl': '',
            '081': '',
            'SeleAtribDipl': '',
            '083': '',
            '084': '',
            'ModAtribDipl': '',
            'Mar Trei enga': '',
            '091': '',
            'SeleAtribEnga': '',
            '093': '',
            '094': '',
            'ModAtribEnga': '',
            'Mar Trei forti': '',
            '101': '',
            'SeleAtribFort': '',
            '103': '',
            '104': '',
            'ModAtribFort': '',
            'Mar Trei furti': '',
            '111': '',
            'SeleAtribFurt': '',
            '113': '',
            '114': '',
            'ModAtribFurt': '',
            'Mar Trei guerra': '',
            '121': '',
            'SeleAtribGuer': '',
            '123': '',
            '124': '',
            'ModAtribGuer': '',
            'Mar Trei ini': '',
            '131': '',
            'SeleAtribInic': '',
            '133': '',
            '134': '',
            'ModAtribInic': '',
            'Mar Trei inti': '',
            '141': '',
            'SeleAtribInti': '',
            '143': '',
            '144': '',
            'ModAtribInti': '',
            'Mar Trei intu': '',
            '151': '',
            'SeleAtribIntu': '',
            '153': '',
            '154': '',
            'ModAtribIntu': '',
            'Mar Trei inve': '',
            '161': '',
            'SeleAtribInve': '',
            '163': '',
            '164': '',
            'ModAtribInve': '',
            'Mar Trei joga': '',
            '171': '',
            'SeleAtribJoga': '',
            '173': '',
            '174': '',
            'ModAtribJoga': '',
            'Mar Trei ladi': '',
            '181': '',
            'SeleAtribLadi': '',
            '183': '',
            '184': '',
            'ModAtribLadi': '',
            'Mar Trei luta': '',
            '191': '',
            'SeleAtribLuta': '',
            '193': '',
            '194': '',
            'ModAtribLuta': '',
            'Mar Trei misti': '',
            '201': '',
            'SeleAtribMist': '',
            '203': '',
            '204': '',
            'ModAtribMist': '',
            'Mar Trei nobre': '',
            '221': '',
            'SeleAtribNobr': '',
            '223': '',
            '224': '',
            'ModAtribNobr': '',
            'Mar Trei ofi1': '',
            'Ofício 1': '',
            '231': '',
            'SeleAtribOfi1': '',
            '233': '',
            '234': '',
            'ModAtribOfi1': '',
            'Mar Trei ofi2': '',
            'Ofício_2': '',
            '241': '',
            'SeleAtribOfi2': '',
            '243': '',
            '244': '',
            'ModAtribOfi2': '',
            'Mar Trei perce': '',
            '251': '',
            'SeleAtribPerc': '',
            '253': '',
            '254': '',
            'ModAtribPerc': '',
            'Mar Trei pilo': '',
            '211': '',
            'SeleAtribPilo': '',
            '213': '',
            '214': '',
            'ModAtribPilo': '',
            'Mar Trei ponta': '',
            '261': '',
            'SeleAtribPont': '',
            '263': '',
            '264': '',
            'ModAtribPont': '',
            'Mar Trei refle': '',
            '271': '',
            'SeleAtribRefl': '',
            '273': '',
            '274': '',
            'ModAtribRefl': '',
            'Mar Trei reli': '',
            '281': '',
            'SeleAtribReli': '',
            '283': '',
            '284': '',
            'ModAtribReli': '',
            'Mar Trei sobre': '',
            '291': '',
            'SeleAtribSobr': '',
            '293': '',
            '294': '',
            'ModAtribSobr': '',
            'Mar Trei vonta': '',
            '301': '',
            'SeleAtribVont': '',
            '303': '',
            '304': '',
            'ModAtribVont': '',
            '010': '',
            '020': '',
            '030': '',
            '040': '',
            '050': '',
            '060': '',
            '070': '',
            '080': '',
            '090': '',
            '100': '',
            '110': '',
            '120': '',
            '130': '',
            '140': '',
            '150': '',
            '160': '',
            '170': '',
            '180': '',
            '190': '',
            '200': '',
            '220': '',
            '230': '',
            '240': '',
            '250': '',
            '210': '',
            '260': '',
            '270': '',
            '280': '',
            '290': '',
            '300': '',
            'SeleAtribMagia': '',
            'ModAtribMagia': '',
            'Carga Usada': '',
            'Reset': '',
            }



def atribui_personagem_pdf(personagem):


    dict_pdf = {'Nome do Personagem': personagem.nome,
            'Nome do Jogador': personagem.jogador,
            'Raca do Personagem': personagem.raca.nome,
            'Origem do Personagem': personagem.origem.nome,
            'Classe\\(s\\) do personagem': personagem.classe.nome, # Não aparece
            'Divindade': personagem.divindade.nome,
            'ModFor': str(personagem.atributos['Força'].modificador),
            'ModDes': str(personagem.atributos['Destreza'].modificador),
            'ModCon': str(personagem.atributos['Constituição'].modificador),
            'ModInt': str(personagem.atributos['Inteligência'].modificador),
            'ModSab': str(personagem.atributos['Sabedoria'].modificador),
            'ModCar': str(personagem.atributos['Carisma'].modificador),
            'Pontos de Vida m#C3#A1ximos': str(personagem.PV.max),
            'Pontos de Vida atuais': str(personagem.PV.atual),
            'Pontos de Mana m#C3#A1ximos': str(personagem.PM.max),
            'Pontos de Mana atuais': str(personagem.PM.atual),
            # Ataques Padrões
            'Ataque 1': '',
            'Bonus do ataque 1': '',
            'Dano causado pelo ataque 1': '',
            'Margem de cr#C3#ADtico e multiplicador 1': '',
            'Tipo de dano do ataque 1': '',
            'Alcance do ataque 1': '',
            'Ataque 2': '',
            'Bonus do ataque 2': '',
            'Dano causado pelo ataque 2': '',
            'Margem de cr#C3#ADtico e multiplicador 2': '',
            'Tipo de dano do ataque 2': '',
            'Alcance do ataque 2': '',
            'Ataque 3': '',
            'Bonus do ataque 3': '',
            'Dano causado pelo ataque 3': '',
            'Margem de cr#C3#ADtico e multiplicador 3': '',
            'Tipo de dano do ataque 3': '',
            'Alcance do ataque 3': '',
            'Ataque 4': '',
            'Bonus do ataque 4': '',
            'Dano causado pelo ataque 4': '',
            'Margem de cr#C3#ADtico e multiplicador 4': '',
            'Tipo de dano do ataque 4': '',
            'Alcance do ataque 4': '',
            'Ataque 5': '',
            'Bonus do ataque 5': '',
            'Dano causado pelo ataque 5': '',
            'Margem de cr#C3#ADtico e multiplicador 5': '',
            'Tipo de dano do ataque 5': '',
            'Alcance do ataque 5': '',
            'Proficiencias e outras caracteristicas': '',
            'Experiencia total do personagem': '',
            'Deslocamento do personagem': str(personagem.deslocamento),
            # Inventario
            'Item 1': '',
            'Quantidade Item 1': '',
            'Slots Item 1': '',
            'Item 2': '',
            'Quantidade Item 2': '',
            'Slots Item 2': '',
            'Item 3': '',
            'Quantidade Item 3': '',
            'Slots Item 3': '',
            'Item 4': '',
            'Quantidade Item 4': '',
            'Slots Item 4': '',
            'Item 5': '',
            'Quantidade Item 5': '',
            'Slots Item 5': '',
            'Item 6': '',
            'Quantidade Item 6': '',
            'Slots Item 6': '',
            'Item 7': '',
            'Quantidade Item 7': '',
            'Slots Item 7': '',
            'Item 8': '',
            'Quantidade Item 8': '',
            'Slots Item 8': '',
            'Item 9': '',
            'Quantidade Item 9': '',
            'Slots Item 9': '',
            'Item 10': '',
            'Quantidade Item 10': '',
            'Slots Item 10': '',
            'Item 11': '',
            'Quantidade Item 11': '',
            'Slots Item 11': '',
            'Item 12': '',
            'Quantidade Item 12': '',
            'Slots Item 12': '',
            'Item 13': '',
            'Quantidade Item 13': '',
            'Slots Item 13': '',
            'Item 14': '',
            'Quantidade Item 14': '',
            'Slots Item 14': '',
            'Item 15': '',
            'Quantidade Item 15': '',
            'Slots Item 15': '',
            'Item 16': '',
            'Quantidade Item 16': '',
            'Slots Item 16': '',
            'Item 17': '',
            'Quantidade Item 17': '',
            'Slots Item 17': '',
            'Tibares': '',
            'Limite de carga': '',
            # Descrições
            'Descricao': '',
            'Habilidades de raca e origem': '',
            'Habilidades de Classe e poderes': '',
            'Teste de resistencias': '',
            'Magias': '',
            'Anotacoes': '',
            'Lv': str(personagem.nivel),
            'CA': 'a',
            'Base CA': 'b', # Nada
            'arm pesa': 'c', # Nada
            'SeleAtribDefe': 'Sabedoria',
            'ModAtribDefe': '13', # Modificador em baixo de Des
            'Arm': '',
            'Esc': '',
            'Arm1': '',
            'Esc2': '',
            'B': 'B',
            'Outros B': 'outr',
            'PArmTotal': 'PAr',
            'Armadura': 'ar',
            'Pa': 'pa',
            'Escudo': 'es',
            'Pe': 'pe',
            'SeleTamanho': 'Grande',
            'ModFurtTam': '',
            'ModManTam': '',
            # Acrobacia
            'Mar Trei acro': ['Yes'], # Marcador de Treinado
            '011': '', # 1/2 do nivel
            'SeleAtribAcro': 'Sab', # sla
            '013': '1', # Treino
            '014': '2', # Outros
            'ModAtribAcro': '3', # Nada
            # Adestramento
            'Mar Trei ades': ['Yes'],
            # '021': '',
            # 'SeleAtribAdes': '',
            '023': '1',
            '024': '2',
            #'ModAtribAdes': '',
            # Atletismo
            'Mar Trei atle': '',
            '031': '',
            'SeleAtribAtle': '',
            '033': '',
            '034': '',
            'ModAtribAtle': '',
            # Atuação
            'Mar Trei atua': '',
            '041': '',
            'SeleAtribAtua': '',
            '043': '',
            '044': '',
            'ModAtribAtua': '',
            # Cavalgar
            'Mar Trei caval': '',
            '051': '',
            'SeleAtribCava': '',
            '053': '',
            '054': '',
            'ModAtribCava': '',
            # Conhecimento
            'Mar Trei conhe': '',
            '061': '',
            'SeleAtribConh': '',
            '063': '',
            '064': '',
            'ModAtribConh': '',
            # Cura
            'Mar Trei cura': '',
            '071': '',
            'SeleAtribCura': '',
            '073': '',
            '074': '',
            'ModAtribCura': '',
            # Diplomacia
            'Mar Trei dipl': '',
            '081': '',
            'SeleAtribDipl': '',
            '083': '',
            '084': '',
            'ModAtribDipl': '',
            # Enganação
            'Mar Trei enga': '',
            '091': '',
            'SeleAtribEnga': '',
            '093': '',
            '094': '',
            'ModAtribEnga': '',
            # Fortitude
            'Mar Trei forti': '',
            '101': '',
            'SeleAtribFort': '',
            '103': '',
            '104': '',
            'ModAtribFort': '',
            # Furtividade
            'Mar Trei furti': '',
            '111': '',
            'SeleAtribFurt': '',
            '113': '',
            '114': '',
            'ModAtribFurt': '',
            # Guerra
            'Mar Trei guerra': '',
            '121': '',
            'SeleAtribGuer': '',
            '123': '',
            '124': '',
            'ModAtribGuer': '',
            # Iniciativa
            'Mar Trei ini': '',
            '131': '',
            'SeleAtribInic': '',
            '133': '',
            '134': '',
            'ModAtribInic': '',
            # Intimidação
            'Mar Trei inti': '',
            '141': '',
            'SeleAtribInti': '',
            '143': '',
            '144': '',
            'ModAtribInti': '',
            # Intuição
            'Mar Trei intu': '',
            '151': '',
            'SeleAtribIntu': '',
            '153': '',
            '154': '',
            'ModAtribIntu': '',
            # Investigação
            'Mar Trei inve': '',
            '161': '',
            'SeleAtribInve': '',
            '163': '',
            '164': '',
            'ModAtribInve': '',
            # Jogatina
            'Mar Trei joga': '',
            '171': '',
            'SeleAtribJoga': '',
            '173': '',
            '174': '',
            'ModAtribJoga': '',
            # Ladinagem
            'Mar Trei ladi': '',
            '181': '',
            'SeleAtribLadi': '',
            '183': '',
            '184': '',
            'ModAtribLadi': '',
            # Luta
            'Mar Trei luta': '',
            '191': '',
            'SeleAtribLuta': '',
            '193': '',
            '194': '',
            'ModAtribLuta': '',
            # Misticismo
            'Mar Trei misti': '',
            '201': '',
            'SeleAtribMist': '',
            '203': '',
            '204': '',
            'ModAtribMist': '',
            # Nobreza
            'Mar Trei nobre': '',
            '221': '',
            'SeleAtribNobr': '',
            '223': '',
            '224': '',
            'ModAtribNobr': '',
            # Oficio 1
            'Mar Trei ofi1': '',
            'Ofício 1': '', # especificação
            '231': '',
            'SeleAtribOfi1': '',
            '233': '',
            '234': '',
            'ModAtribOfi1': '',
            # Oficio 2
            'Mar Trei ofi2': '',
            'Ofício_2': '', # especificação
            '241': '',
            'SeleAtribOfi2': '',
            '243': '',
            '244': '',
            'ModAtribOfi2': '',
            # Percepção
            'Mar Trei perce': '',
            '251': '',
            'SeleAtribPerc': '',
            '253': '',
            '254': '',
            'ModAtribPerc': '',
            # Pilotagem
            'Mar Trei pilo': '',
            '211': '',
            'SeleAtribPilo': '',
            '213': '',
            '214': '',
            'ModAtribPilo': '',
            # Pontaria
            'Mar Trei ponta': '',
            '261': '',
            'SeleAtribPont': '',
            '263': '',
            '264': '',
            'ModAtribPont': '',
            # Reflexo
            'Mar Trei refle': '',
            '271': '',
            'SeleAtribRefl': '',
            '273': '',
            '274': '',
            'ModAtribRefl': '',
            # Religião
            'Mar Trei reli': '',
            '281': '',
            'SeleAtribReli': '',
            '283': '',
            '284': '',
            'ModAtribReli': '',
            # Sobrevivência
            'Mar Trei sobre': '',
            '291': '',
            'SeleAtribSobr': '',
            '293': '',
            '294': '',
            'ModAtribSobr': '',
            # Vontade
            'Mar Trei vonta': '',
            '301': '',
            'SeleAtribVont': '',
            '303': '',
            '304': '',
            'ModAtribVont': '',
            # Totais
            # '010': '',
            # '020': '',
            # '030': '',
            # '040': '',
            # '050': '',
            # '060': '',
            # '070': '',
            # '080': '',
            # '090': '',
            # '100': '',
            # '110': '',
            # '120': '',
            # '130': '',
            # '140': '',
            # '150': '',
            # '160': '',
            # '170': '',
            # '180': '',
            # '190': '',
            # '200': '',
            # '220': '',
            # '230': '',
            # '240': '',
            # '250': '',
            # '210': '',
            # '260': '',
            # '270': '',
            # '280': '',
            # '290': '',
            # '300': '',
            'SeleAtribMagia': 'Sab',
            'ModAtribMagia': '',
            'Carga Usada': '',
            'Reset': '',
            }
    
    return dict_pdf



def preencher_campos_selecao(pdf_path, dados):
    template_pdf = pdfrw.PdfReader(pdf_path)
    
    for page in template_pdf.pages:
        annotations = page['/Annots']
        if annotations:
            for annotation in annotations:
                if annotation['/Subtype'] == '/Widget':
                    field_name = annotation['/T']
                    if field_name[1:-1] in dados:
                        field_value = dados[field_name[1:-1]]
                        if isinstance(field_value, list):  # Para caixas de marcação (checkbox)
                            annotation.update(pdfrw.PdfDict(V=pdfrw.PdfName(field_value[0]))) # nao funciona
                        elif isinstance(field_value, str):  # Para texto básico
                            annotation.update(pdfrw.PdfDict(V=field_value))
                        else: # Para campos selecionáveis
                            annotation.update(pdfrw.PdfDict(V=field_value))

    pdfrw.PdfWriter().write("pdf_preenchido.pdf", template_pdf)


